### ISSUE TITLE
The last line of your README?

### ISSUE THREAD

**Issue by lingfish** [svalgaard/certbot-dns-infoblox#1]
Hi, can you clarify your comments around public databases?  Perhaps around security etc?

**Comment by svalgaard** [comment]
I assume that you refer to this line:
´´´
Note that all your issued certificates can be found in public databases, e.g., crt.sh.
´´´

All certificates issued by Certificate Authorities as, e.g., Let's Encrypt are added to a distributed database called the [certificate transparency logs](https://certificate.transparency.dev/) (searchable at e.g. [crt.sh](https://crt.sh/)). In particular when issuing internal certificates, you should be careful about revealing names of internal servers, etc.

**Comment by svalgaard** [comment]
I've added a bit more text to README.md to clarify this.

**Comment by lingfish** [comment]
Nice, that was all I was suggesting, thanks :)
